# Generated by Django 6.1.1 on 2026-09-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskzone',
            name='boundary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
